name: Molk

on:
  push:
    branches:
      - master
  repository_dispatch:
    types: Hexo

jobs:
  build:
    name: Deploy Molk
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [13.x]

    steps:
      - name: Checkout self
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Configuration environment
        env:
          HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_PRI}}
          GIT_USER: "Torther"
          GIT_EMAIL: "i@mol.ink"
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "$GIT_USER"
          git config --global user.email "$GIT_EMAIL"

      - name: Checkout source
        run: |
          rm -rf source
          git clone git@github.com:Torther/blogPrivate.git source
          rm -rf ./source/.git
          rm -rf ./source/.github
          rm -rf ./_config.yml
          mv ./source/_config.stellar.yml ./
          mv ./source/_config.site.yml ./_config.yml

      - name: Checkout theme
        run: |
          git clone git@github.com:Torther/hexo-theme-stellar.git themes/stellar
          rm -rf ./themes/stellar/_config.yml

      - name: Cache Node Dependencies
        id: cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{runner.OS}}-npm-caches-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies.
        run: |
          npm install hexo-cli -g
          npm install

      - name: Deploy Github page.
        run: |
          hexo clean
          hexo g
          hexo d
